profileOne:
  title: x264 Video
  container: mp4
  encoded_filename_suffix: x264
  video_command: ffmpeg -i $input_file$ -acodec libfaac -ab 128 -vcodec libx264 -preset fast -crf 22 -threads 0 -y $output_file$
  video_bitrate:
  audio_command:
  audio_bitrate:
  width: 640
  height: 480
  fps: 24
  player: 
  content_type: video/mp4

profileTwo:
 title: WebM Video
 container: webm
 encoded_filename_suffix: vp8
 video_command: ffmpeg -i $input_file$ -acodec libvorbis -preset libvpx-720p -y $output_file$
 video_bitrate:
 audio_command:
 audio_bitrate: 160
 width: 640
 height: 480
 fps: 24
 content_type: video/webm